-- Are there any DB.SCHEMA.TABLE.COLUMNS (TAGS.SECURITY_TAGS.COLUMN_TAG_VALUE) with a value of 'SSN' that do not have a masking policy assigned? --

 

WiTH COLUMN_WITH_TAG AS

    (

    SELECT  OBJECT_DATABASE

            ,OBJECT_SCHEMA

            ,OBJECT_NAME

            ,COLUMN_NAME

    FROM    SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES

    WHERE   TAG_DATABASE = 'TAGS'

    AND     TAG_SCHEMA = 'SECURITY_TAGS'   

    AND     TAG_NAME = 'PII_TYPE'

    AND     TAG_VALUE = 'SSN'

    ),

 

COLUMN_WITH_POLICY AS

    (

    SELECT  REF_DATABASE_NAME   OBJECT_DATABASE

            ,REF_SCHEMA_NAME    OBJECT_SCHEMA

            ,REF_ENTITY_NAME    OBJECT_NAME

            ,REF_COLUMN_NAME    COLUMN_NAME

    FROM    TABLE(HR.INFORMATION_SCHEMA.POLICY_REFERENCES(POLICY_NAME => 'SECURITY_POLICIES.MASKING_POLICIES.SSN_MASK'))

    )

SELECT  *

FROM    COLUMN_WITH_TAG

EXCEPT

SELECT  *

FROM    COLUMN_WITH_POLICY;